### ISSUE TITLE
Push command fails to read versioning

### ISSUE THREAD

**Issue by MPTG94** [emgarten/Sleet#1]
When using 'sleet push' on a directory filled with packages pulled from the nuget.org V3 feed, I encounter the following error:

> Package 'D:\Packages\Aaron.Core\3.2.4\Aaron.Core.3.2.4.nupkg' does not contain a valid version: '3.2.4.0'. See https://semver.org/ for details

I am using sleet version 1.0.0

**Comment by emgarten** [comment]
I've changed this from an error to a verbose log message to allow this to work for older packages which have extra trailing zeros such as Aaron.Core, it is fairly common on nuget.org.

You can get the latest version with the fix here:
https://www.myget.org/F/sleet/api/v2/package/Sleet/
