### ISSUE TITLE
Add a prune command

### ISSUE THREAD

**Issue by kzu** [emgarten/Sleet#10]
A new `prune` command would be very useful to save on storage specially for CI-populated feeds.

Some options (after `slate prune `) that would be great:

* `-i|--include`: package id/s to consider for pruning. `*` would mean evaluate all. 
   Can be specified multiple times.
* `-n|--no-downloads`: delete all packages that have zero downloads
* `-m|--max-age`: delete all packages that are older than the given days. When combined with 
  `--no-downloads`, it would only delete old packages if they have no downloads.

**Comment by emgarten** [comment]
I like the idea of a prune command.

For pruning on downloads I'm not sure how to get this info for azure storage, do you know if that is possible?

Max age would work, and I like the wildcards for include.  I think this would also need a way to specify a limit such as last 10.

This could also work by storing pruning settings and pinned versions on the feed and automatically pruning each package id that is pushed or updated.

**Comment by kzu** [comment]
Ha, pinning would be great too!

Good point on getting the stats. I thought that since you already provide a `stats` command, that info was already being fetched somehow :). I'm not familiar with the storage API/services, but maybe there's a way to add automatic telemetry (like adding appinsights to an azure function) or even get the raw download info for a blob? Will see if I can investigate.

If the `limit` means "remove at most X" I'm not sure that's too useful. Say after 3 months of CI I get an email from Azure saying "you will start paying X for storage", how would I know what number to use there?

Now that I think of it, maybe there should be a `-p|--prerelease` to limit the pruning to prereleases only, since typically CI builds are labeled as such?

**Comment by kzu** [comment]
I've been researching a bit, but the metrics that blob storage provides (in the $Metrics* tables) is not per-blob but aggregate per API (i.e. GetBlob), for the billing aspect, not really for tracking.

Maybe I'm missing something, but I thought this should have been pretty easy to do :\.

**Comment by emgarten** [comment]
Interested, I hadn't checked that before. I know when using a CDN in front of a storage account there are logs, but something else would be needed to parse and store that info so that all logs did not need to be parsed each time.

**Comment by skarllot** [comment]
I like the idea.

The problem is the downloads counting on S3, because it needs a log parsing.

**Comment by emgarten** [comment]
Package retention has been added in https://www.nuget.org/packages/Sleet/3.1.8
