### ISSUE TITLE
Question About 403 Errors

### ISSUE THREAD

**Issue by hounddog22030** [emgarten/Sleet#100]
We are building in CodeBuild on AWS.

Generally everything is working.  But we are getting a crapton of 403 errors.

We have a NuGet.Config which has nuget.org first (I'm pretty sure the order does not matter)
and our cloudfront url as the next PackageSources.

We are getting 403 errors when it looks for packages not in the sleet repo.

These packages should be resolved on nuget.org.

These errors are noisy and make it difficult to debug real problems.

Is there something better we can do to get rid of all these 403s?

[Container] 2020/01/08 06:19:44 Running command dotnet restore --ignore-failed-sources 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/newtonsoft.json/index.json'. 
  Response status code does not indicate success: 403 (Forbidden). 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/yadayada.autoparts.entity/index.json'. 
  Response status code does not indicate success: 403 (Forbidden). 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/system.componentmodel.annotations/index.json'. 
  Response status code does not indicate success: 403 (Forbidden). 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/newtonsoft.json/index.json'. 
  Response status code does not indicate success: 403 (Forbidden). 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/yadayada.autoparts.entity/index.json'. 
  Response status code does not indicate success: 403 (Forbidden). 
  Retrying 'FindPackagesByIdAsync' for source 'http://d1rf46e0s0qx8w.cloudfront.net/flatcontainer/system.componentmodel.annotations/index.json'. 
  Response status code does not indicate success: 403 (Forbidden).

**Comment by emgarten** [comment]
This looks similar to https://github.com/emgarten/Sleet/issues/96

Is your S3 bucket or cloudfront set to only allow certain paths under flatcontainer?

I haven't haven't used cloudfront on top of a sleet feed to hit this issue. If we can find out what is causing this I would like to add docs on how to set this up and avoid this problem.

**Comment by hounddog22030** [comment]
Is there any possibility it has anything to do with not running the init with "with-catalog"?

**Comment by hounddog22030** [comment]
> Is your S3 bucket or cloudfront set to only allow certain paths under flatcontainer?

We didn't do anything explicit to set it that way.  Would that be the default?

**Comment by emgarten** [comment]
> Is there any possibility it has anything to do with not running the init with "with-catalog"?

No, the catalog isn't read by NuGet client. It is purely for recording keeping purposes.

> We didn't do anything explicit to set it that way. Would that be the default?

I don't know the defaults for cloudfront. For the S3 bucket if Sleet created it then it will have a public read-only policy for all paths.

**Comment by hounddog22030** [comment]
We’re going to develop a reusable cloud formation template. Maybe when we
have that someone might be able to reproduce it. Or at the very least we’ll
be making a contribution to the effort.

**Comment by emgarten** [comment]
@hounddog22030 any progress on tracking down what was causing these 403s?

**Comment by hounddog22030** [comment]
Hi.  Sorry for not letting you know.  I believe I slowly came to the realization that the 403s were just part of the Nuget process where it looks for everything in each repo until it finds it.  So, we were not storing 3rd party packages in our sleet deployment but pulling them from nuget.org.

We're not using dotnet restore --ignore-failed-sources and I guess that the 403s are just part of the game.

But, we did develop a CloudFormation template which is reusable albeit one caveat, the Lambda Function that contains the Zip file is obviously external to the template.

I have uploaded it:  https://gist.github.com/hounddog22030/ed33bc1935369465a8f783c8ac7cf7bc

If someone wanted to rewrite the function in a language that allow the lambda function to be embedded (e.g. node.js), I could include the whole enchilada in the template.

The function is literally the same as the one on here: http://kynatro.com/blog/2018/01/03/a-step-by-step-guide-to-creating-a-password-protected-s3-bucket/

**Comment by emgarten** [comment]
NuGet checks every feed for all package ids in parallel during restore. If the package doesn't exist on the feed a 404 should be returned.

Thanks for sharing the function

**Comment by Ed-MacDonald** [comment]
The issue with the 403's is because S3 returns a 403 if an object doesn't exist and you don't have the ListBucket permission.  If you add `s3:ListBucket` to the bucket policy, S3 will return 404's and the auth challenge in VS will stop.

**Comment by hounddog22030** [comment]
I changed the bucket policy as below and same error happens.

To be clear this is on items that do not exist in the repo/bucket, but rather should be found on nuget.org.

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E16E9J3RWY96CH"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::partlookupbyupc-sleetbucket-44p72oamme1t/*"
        }
    ]
}`

**Comment by Ed-MacDonald** [comment]
You'll need to specify the bucket in the resource list, not just the wildcard.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal":
      {
        "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity xxxxxxxxxxxxxxx"
      },
      "Action": "s3:*",
      "Resource": [
	     "arn:aws:s3:::partlookupbyupc-sleetbucket-xxxxxxxxxxxxxx", 
		 "arn:aws:s3:::partlookupbyupc-sleetbucket-xxxxxxxxxxxxxx/*"
	  ]
    }
  ]
}

```

**Comment by hounddog22030** [comment]
> You'll need to specify the bucket in the resource list, not just the wildcard.

You're a genius!  Thanks!
