### ISSUE TITLE
Usage question...

### ISSUE THREAD

**Issue by IshayLevy** [emgarten/Sleet#101]
I'm getting accesskey and secretkey externally. How do I use sleet?

**sleet download -o _myfolder_ -p accessKeyId=_mykeyid_ -p secretAccessKey=_mysecretkey_**

doesn't seem to work for me...

**Comment by emgarten** [comment]
Start by using `sleet.json` to configure the feed. You can find help on that here: https://github.com/emgarten/Sleet/blob/master/doc/feed-type-s3.md

Once you have that working you can pass the same values on the command line if needed. From your example it looks like you are missing some properties, including the bucket.

**Comment by IshayLevy** [comment]
Hi, thanks for your reply.
The missing properties are defined in my sleet.json.
I understood that you can override/add properties with the -p option. Was I wrong?

**Comment by emgarten** [comment]
> I understood that you can override/add properties with the -p option. Was I wrong?

That's correct, it should work then.  Are you able to get it to work if you define the keys in sleet.json? Does init or validate work?

**Comment by IshayLevy** [comment]
> Are you able to get it to work if you define the keys in sleet.json?

Yes, it works fine.

> Does init or validate work?

Same issue as with download.

> What errors are you seeing? Are they around verifying the keys?

No errors - my inline parameters are simply ignored, The code always uses the sleet.json parameters.

I suspect it might be related to the ResolveTokensInSettingsJson() method of the **SettingUtility**:

`
public static void ResolveTokensInSettingsJson(JObject json, Dictionary<string, string> mappings)
        {
            var properties = json.Descendants().Where(e => e.Type == JTokenType.Property)
                .Select(e => (JProperty)e)
                .ToList();
            foreach (var prop in properties)
            {
                if (prop.Value.Type == JTokenType.String)
                {
                    prop.Value = ResolveTokens(prop.Value.ToString(), mappings);
                }
            }
        }
`

Why passing prop.**Value**.ToString()? shouldn't it be prop.**Key**.ToString() ?

**Comment by emgarten** [comment]
> Can you please specify how to use Sleet (e.g. push) with all sleet.json parameters inlined?

That should work.

Would you removing bucketName from the config and passing that in from the command line? I'm wondering if the keys need escaping.

**Comment by IshayLevy** [comment]
When deleting the bucketName from the config and using:

> sleet push "C:\mypack.nupkg" -s feed -f -p bucketName=mybucket

I'm getting:

> [System.ArgumentException] Missing bucketName for Amazon S3 account.

BTW
Is there a way to download a specific package/version?

**Comment by emgarten** [comment]
Try `sleet push "C:\mypack.nupkg" -s feed -f -p SLEET_FEED_BUCKETNAME=mybucket`

**Comment by IshayLevy** [comment]
Thanks!
`sleet push "C:\mypack.nupkg" -s feed -f -p SLEET_FEED_BUCKETNAME=mybucket`
This works.

Is there a way to download a specific package/version?

**Comment by emgarten** [comment]
You can download a package directly by constructing the URL

`https://<url>/<folder>/flatcontainer/{id-lower}/{version-lower}/{id-lower}.{version-lower}.nupkg`

The download command is intended as a way to backup the feed, not as a replacement for NuGet client or other tools which consume the feed.

**Comment by IshayLevy** [comment]
Thanks!
