### ISSUE TITLE
Symbol server case sensitivity issues

### ISSUE THREAD

**Issue by iderbyshev** [emgarten/Sleet#102]
When publishing a symbol package to the Azure feed, Sleet preserves the casing of file names and creates the PDB hash directory in uppercase.   
So the PDB path looks like this:  
`https://mysymbols.blob.core.windows.net/nuget/symbols/My.Library.pdb/7A9D4CD67D0946D48B6D815D13E5D0C8ffffffff/My.Library.pdb`  
But Visual Studio uses another casing schema when trying to download symbol files:  
`https://mysymbols.blob.core.windows.net/nuget/symbols/my.library.pdb/7a9d4cd67d0946d48b6d815d13e5d0c8FFFFFFFF/my.library.pdb`  
As a result, on Azure Blobs it gets 404 because Azure Blob Storage is case sensitive.  
I'm not sure that it is an expected behavior, is there any workaround?

**Comment by emgarten** [comment]
What version of VS are you using? Are the hashes always lowercase or does it depend on the pdb?

**Comment by iderbyshev** [comment]
VS 16.3.5
Looks like the pattern it uses is always the same:  
`GET /download/symbols/microsoft.aspnetcore.http.abstractions.pdb/706c31cd08b8489195d29de7a6877750FFFFFFFF/microsoft.aspnetcore.http.abstractions.pdb HTTP/1.1 `   
`GET /nuget/symbols/mongodb.driver.pdb/40292070252642e3a35afbe61bc137b9FFFFFFFF/mongodb.driver.pdb HTTP/1.1  `

**Comment by emgarten** [comment]
Are you able to tell if the hash coming from the dll and pdb are identical? Or is the symbol server expected to be case insensitive?

**Comment by iderbyshev** [comment]
What I see is that both Rider & VS send requests with lowercase hash (except the trailing FFFFFFFF) & filename. At least on my Windows machine.  How can I check the hash values in the pdb & dll?
