### ISSUE TITLE
Implement retention policy

### ISSUE THREAD

**Issue by sebastienros** [emgarten/Sleet#104]
Delete packages based on:
- older than last n pre-release versions
- older than last n release versions

Not by date. Just in order to keep a limited set of packages.

**Comment by emgarten** [comment]
I like the version based approach to limit packages, this would be easy to use and straight forward to implement in Sleet.

It could work by:
* Store the release/pre-release limit values on the feed in settings. This can be set with the `feed-settings` command for any value, or a new command could be added to make surface this.
* After a push operation check for packages over the limit by using `sleet.packageindex.json`
* Apply deletes
* Commit all feed changes

**Comment by LordMike** [comment]
Possibly add a `retention-clean` command that has a `--no-op` / `--dry-run` option.

Concerns / use cases:

* Keep last N pre-release versions, counted for each Major.Minor.Patch version (`1.0.1-alpha1` and `1.0.2-alpha1` count as 1 pre-release for versions 1 and 2 ..)
  * Alternate: Keep last N pre-release versions, counted globally
  * Alternate: Keep last N pre-release versions for each off ..
    * For the last A major versions
    * For their last B minor versions
    * For their last C patch versions
* Keep last N major/minor/patch versions (`Major.Minor.Patch`)
  * Alternate: Keep all released versions (ie. disable retention policies for released)

The idea being that we might want to keep the last 50 versions

**Comment by emgarten** [comment]
Package retention has been added in https://www.nuget.org/packages/Sleet/3.1.8

@LordMike I'm going to start with the basic scenarios for package retention. I've included `--dry-run` per your suggestion, I think that is a great idea. For more complex pruning scenario I'm interested in how these could be described or if an extension point is needed for this.
