### ISSUE TITLE
Request support for PackageIcon

### ISSUE THREAD

**Issue by midicine** [emgarten/Sleet#107]
It seems sleet doesn't support the `<PackageIcon>` attribute in `.csproj`. 

I've been trying to push a package containing project with following settings in `.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <Authors>xxxxxx</Authors>
    <Description>xxxxx.</Description>
    <Copyright>xxxxxx</Copyright>
    <PackageProjectUrl>xxxxx</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
```
The package can be successfully published to my customized AWS S3 nuget server, but the icon just doesn't show up.

Any ideas?

**Comment by emgarten** [comment]
The package icon could be extracted during push and hosted on the feed. 

PackageIcon was added to NuGet after Sleet was originally created. It should be straight forward to add as a new feature.
