### ISSUE TITLE
Null reference exception when using AWS role profile from ~/.aws/credentials

### ISSUE THREAD

**Issue by volodymyr-oliinyk** [emgarten/Sleet#109]
Sleet.json
{
  "username": "xxxx",
  "useremail": "xxx@mail.com",
  "sources": [
    {
      "name": "develop",
      "type": "s3",
      "path": "https://s3.amazonaws.com/<bucket>/",
      "bucketName": "<bucket>",
      "region": "eu-west-1",
      "profileName": "nuget"
    }
  ]
}

.credentials
[nuget]
role_arn = arn:aws:iam::1234456789:role/nuget-bucket-reader-writer
source_profile = dev

**Comment by emgarten** [comment]
@volodymyr-oliinyk would you run Sleet with ``--verbose`` and share the stack trace?

**Comment by emgarten** [comment]
Let me know if you are able to get a stacktrace for where this is failing
