### ISSUE TITLE
Support a badge

### ISSUE THREAD

**Issue by mattleibow** [emgarten/Sleet#111]
It will be really awesome if there was a "badge" that was created when managing packages.

Then, I can actually link to that on GitHub readmes and things.

A "preview" and a "stable" for each ID

**Comment by emgarten** [comment]
I like this idea. At push time Sleet could generate badge images and put them under a path similar to:

```
<feed>/badges/v/<packageName>
<feed>/badges/vpre/<packageName>
```

Any ideas on what library could be used to generate the images?

**Comment by mattleibow** [comment]
SkiaSharp could be good... I just released a nice new version: https://github.com/mono/SkiaSharp

So I just whipped up a very rough repo for this... Having to take a little pause as I do have to do some work hehe

https://github.com/mattleibow/BadgeGenerator

It draws the "flat" badge now, but not yet text: 

![](https://img.shields.io/badge/label-message-green)

**Comment by mattleibow** [comment]
In fact, why even bother with "generation"? Just use an SVG and template the thing:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="96" height="20">
    <linearGradient id="s" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <clipPath id="r">
        <rect width="96" height="20" rx="3" fill="#fff"/>
    </clipPath>
    <g clip-path="url(#r)">
        <rect width="37" height="20" fill="#555"/>
        <rect x="37" width="59" height="20" fill="#97ca00"/>
        <rect width="96" height="20" fill="url(#s)"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110">
        <text x="195" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="270">label</text>
        <text x="195" y="140" transform="scale(.1)" textLength="270">label</text>
        <text x="655" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="490">message</text>
        <text x="655" y="140" transform="scale(.1)" textLength="490">message</text>
    </g>
</svg>
```

**Comment by newbe36524** [comment]
Maybe we can just submit some code to https://github.com/badges/shields to support custom nuget badge.
And then we can get badge from https://shields.io/. 
Keep this repo simple maybe.

**Comment by emgarten** [comment]
@newbe36524 I don't see other self hosted feeds like this on shields.io, otherwise that would be the best route.

**Comment by emgarten** [comment]
I've added support for badges, you can get the latest Sleet release and try it by enabling the `badgesenabled` source setting. I wrote up a short doc for it here: https://github.com/emgarten/Sleet/blob/master/doc/badges.md

By default this feature will be off until the setting it turned on, we can look at enabling it by default once it gets some usage.

Thanks for the idea and pointers on this @mattleibow

**Comment by mattleibow** [comment]
YAY!

Thanks for this! Great tool and now this makes it even better! I need to update a bunch of release pipelines 😄
