### ISSUE TITLE
Add support for encryption on objects uploaded to S3

### ISSUE THREAD

**Issue by mungojam** [emgarten/Sleet#115]
Our S3 bucket has a policy that forces AES (or KMS) encryption on all uploaded objects. This means that the current version of sleet doesn't work as it doesn't specify encryption.

As for the solution, I've got it working for our AES encryption case by adding `ServerSideEncryptionMethod = ServerSideEncryptionMethod.AES256` to:

https://github.com/emgarten/Sleet/blob/d19f2eaf4ae02e6ab1262462312342d490afaa62/src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs#L26-L31

and

https://github.com/emgarten/Sleet/blob/d19f2eaf4ae02e6ab1262462312342d490afaa62/src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs#L131-L139

but of course it needs to be configurable.

However, there are a lot of possible options that as you can see in [the AWS docs](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TTransferUtilityUploadRequest.html).

I can submit a PR tomorrow probably, are you happy if it just supports AES for now and throws for any of the other options? So the user could only specify `AES256` or `None` (current behaviour which would stay the default).

**Comment by emgarten** [comment]
Thanks for explaining the settings and linking the docs.

> if it just supports AES for now and throws for any of the other options? So the user could only specify AES256 or None (current behaviour which would stay the default).

This sounds like a good approach, other options can be added later if needed.

For the config are you picturing this as a top level setting:

```json
{
  "sources": [
    {
      "name": "feed",
      "type": "s3",
      "path": "https://s3.amazonaws.com/my-bucket-feed/",
      "bucketName": "my-bucket-feed",
      "region": "us-west-2",
      "encryption": "AES"
    }
  ]
}
```

Or do you think other options from TransferUtilityUploadRequest might need to be set in the future? If so we could put those settings into another object in the config:

```json
{
  "sources": [
    {
      "name": "feed",
      "type": "s3",
      "path": "https://s3.amazonaws.com/my-bucket-feed/",
      "bucketName": "my-bucket-feed",
      "region": "us-west-2",
      "uploadRequest": {
            "serverSideEncryptionMethod": "AES256"
      }
    }
  ]
}
```

**Comment by emgarten** [comment]
How are you consuming the encrypted feed? Are you serving the feed through a server side piece that decrypts it for the NuGet client?

**Comment by mungojam** [comment]
> How are you consuming the encrypted feed? Are you serving the feed through a server side piece that decrypts it for the NuGet client?

It's through cloudfront which automatically decrypts AES encrypted files (but not KMS currently).

I may also just use the S3 endpoint directly so that it can go over direct connect. I think that will work with your current design. That's better than the S3 website hosting which doesn't support Https.

**Comment by mungojam** [comment]
I don't forsee needing other request options for myself in future as I now have it working with just that one, so up to you if you want to leave it open for other options in a nested structure.

I probably won't get back to this till next weekend by the way. It's a bit of a side project. I'm trying to do the same for python at the same time but that has other complications 🙂

**Comment by emgarten** [comment]
> I don't forsee needing other request options for myself in future as I now have it working with just that one, so up to you if you want to leave it open for other options in a nested structure.

Top level would be fine then. I appreciate the PRs 😄
