### ISSUE TITLE
Add support for default windows authenticated / kerberos proxy

### ISSUE THREAD

**Issue by mungojam** [emgarten/Sleet#119]
We use an authenticated proxy that uses our windows credentials. To get this to work from .net core, all we have to do is add:

`WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultCredentials;`

I've checked that Sleet works fine with the above when I set it on app startup, however I'm guessing that the above might break other people's proxy setups. Should it be a top level option?

**Comment by emgarten** [comment]
Let's create a `proxy` section in the local `sleet.json` config.

```json
{
  "proxy": {
    "useDefaultCredentials": true
  },
  "sources": [
  ]
}
```

The env var equivalent would be `SLEET_FEED_PROXY_USEDEFAULTCREDENTIALS`

Does that work for your scenarios?

Looking at the NuGet client code, it adds the default credentials for the proxy, but only when a proxy is configured but no credentials were given. So it is probably safest to not add this all the time as you mentioned. My guess is that more settings will get added under proxy over time for sleet.

https://github.com/NuGet/NuGet.Client/blob/d70e1f5475c9915f10ac4503553972d9bb988ce9/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L76

**Comment by mungojam** [comment]
that works for me thanks. Will you have time to add it? I can do it at some point, but it probably won't be for a while.

I've just had the cool milestone of getting our existing package repo synced across to S3 using my manually tweaked version. It processed our 2GB worth of packages in a nicely quick time, and when I ran the sync again it was very quick indeed, < 3 seconds! Nice work :)

**Comment by emgarten** [comment]
The perf work is paying off :smile:

Sure, I can take a look at adding the default proxy creds.

**Comment by emgarten** [comment]
This has been added as part of https://github.com/emgarten/Sleet/pull/126
