### ISSUE TITLE
Example wanted in github action

### ISSUE THREAD

**Issue by newbe36524** [emgarten/Sleet#122]
I want to push package from github .
- [x] I know how to install sleet in github action
- [x] I know how to store serect in github action

but I don`t know how to pass configuration to sleet without a json, as I don`t want to store a json in my source code since it is open source.

**Comment by emgarten** [comment]
Everything in sleet.json can be passed as either an env var or as a command line parameter

Take a look at the docs here: https://github.com/emgarten/Sleet/blob/master/doc/client-settings.md#environment-variables

**Comment by newbe36524** [comment]
Awsome!
I think maybe there should be a word or link in quick start in case of somebody like me.
 e.g. https://github.com/emgarten/Sleet/blob/master/doc/feed-type-azure.md

**Comment by emgarten** [comment]
I agree, the docs could use some improvement. I'll leave this issue open to track it.

Feel free to send a PR for a github action specific example once you get it all working.

**Comment by newbe36524** [comment]
I am glad to share my work about github action in some day by submiting a document in this repo.
You can check my build configuration in advanced, maybe you are interested in.
https://github.com/newbe36524/Newbe.Claptrap/blob/develop/.github/workflows/dev_azure_sleet_nuget.yml
