### ISSUE TITLE
Featurerequest: Support for nuget v2

### ISSUE THREAD

**Issue by ds2edv** [emgarten/Sleet#124]
Hello,

any chance to use it as a v2 feed? 

Would use it with chocolatey but they only support v2 feeds at the moment.

Greetings

**Comment by emgarten** [comment]
the v2 feed format is OData. It uses query parameters and wouldn't work for static files, which means we can't support it in Sleet.

I would really like to see chocolately updated to support NuGet v3 feeds.

https://github.com/chocolatey/choco/issues/508
