### ISSUE TITLE
Simpler configs for quicker setups.

### ISSUE THREAD

**Issue by atheken** [emgarten/Sleet#130]
Hi, this is a really powerful and useful tool, thank you for your work on it.

After "kicking the tires" I am finding that the setup is a bit complicated to understand and seems to be redundant. Specifically in the case where one has many distinct repositories, the "out-of-box" experience seems like it could be improved. 

1. Feeds could use a single URI:

There are lots of config options that are competing within the config file: feedSubPath, path, bucketName, serviceUrl, etc.

```
s3://<bucket>/<root_path>
https://s3.amazonaws.com/<bucket>/<root_path>
https://<bucket>.<region>.s3.amazonaws.com/<root_path>
azure://<bucket>/<root_path>
file://<root_path>
etc.
```

Are there reasons for having multiple settings controlling the final feed destination? Could these be consolidated to a single url and sleet be improved to better interpret these urls? What information is lost by using a single uri for these?

2. For AWS, not all profiles are specified in the shared credentials file. There is an additional shared file called `.aws/config`, into which Roles can be placed. This allows you to maintain a single key for your personal account, and then assume appropriate roles without storing additional credentials on disk. The AWS SDK will properly assume the role (and get temp access credentials) if you include the "SecurityToken" library in the project. This is controlled by the standard environment variables `AWS_PROFILE`. It seems as though sleet does not respect assuming roles in this way, and it makes using the tool in a sub-account much more challenging. I'm happy to try to work on this one if it's something you'd like to improve.

Again, **I really appreciate the work on this tool,** just some observations on friction in setting it up.

**Comment by atheken** [comment]
Welp, I see that some of the reasoning for 1. above is that the public url may differ from the s3 bucket (i.e. s3 via cloudfront), could result in urls in the static files that are pointed directly at s3. I'll search around the documentation and see if there's a way to make this more obvious.

**Comment by emgarten** [comment]
Great feedback, I think getting sleet set up the first time is probably the biggest pain point now. It can be improved.

> above is that the public url may differ from the s3 bucket

That's correct, it allows for an alternative url. This should be optional.

Roles for AWS sounds interesting. I'm no AWS expert, but I'm happy to work with you on any changes there.

Feel free to list any issues or things that are confusing when you go through the docs and we can look at addressing those. PRs are always welcome as well.

**Comment by emgarten** [comment]
@atheken did you come up with any changes that would help here?
