### ISSUE TITLE
Generate shields.io json file for packages

### ISSUE THREAD

**Issue by devhawk** [emgarten/Sleet#132]
shields.io supports rendering a badge from a custom json file (details: https://shields.io/endpoint). Can sleet write out this json file along with the svg file for badges?

Note, the shields.io json file needs to be uncompressed (unless https://github.com/badges/shields/issues/5868 gets fixed)

**Comment by emgarten** [comment]
I've disabled compression for badge svg and json files. Combined with your PR to add badge json files this should all be working now.
