### ISSUE TITLE
IIS published feed needs extra permission care

### ISSUE THREAD

**Issue by omatrot** [emgarten/Sleet#144]
I have followed [this guide](https://github.com/emgarten/Sleet/blob/master/doc/feed-type-local.md) to publish a feed to my local IIS instance.

If I try to access my feed from Visual Studio, I get the following prompt:

![Prompt](https://user-images.githubusercontent.com/4366356/104019151-54e59b80-51bb-11eb-9596-454a77bb0bb8.PNG)

What can I do about that?

**Comment by omatrot** [comment]
This is tied to the index.json file being denied access to the application pool user.
We have to modify security for this to work.

**Comment by omatrot** [comment]
To be able to browse the repo I also need to give 'Everyone' read permission on the packages folder.
That seems wrong to have to do that.

If I don't I get the following error:

Failed to retrieve metadata from source 'http://localhost:5001/feed/search/query?q=&skip=0&take=26&prerelease=false&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).

**Comment by emgarten** [comment]
Are you trying to create a private feed?

If you are trying to create a private feed the credentials would go into nuget.config where the feed is defined. Or if you are using windows auth that would happen automatically.

**Comment by omatrot** [comment]
It will be a private feed, yes. But for now I've never done anything related to that. It will probably use basic authentication.

**Comment by emgarten** [comment]
NuGet supports basic auth, you can configure it in nuget.config.

**Comment by omatrot** [comment]
This works on Windows Server 2012 without any extra care.
