### ISSUE TITLE
[Question] How to synchronize internal nuget directory to a IIS published feed?

### ISSUE THREAD

**Issue by omatrot** [emgarten/Sleet#145]
I have an internal nuget shared folder that I would like to synchronize with an existing externally visible feed [hosted in IIS](https://github.com/emgarten/Sleet/blob/master/doc/feed-type-local.md).

I'm thinking of using a windows scheduled task.

It also seems that at this time I could only use the recreate sleet command. Am I right?

**Comment by emgarten** [comment]
Recreate is meant for upgrading between versions of sleet, or fixing a broken feed.

Sleet would work with the local folder, and then however you are able to sync the local folder with IIS using a different process.

I'm not an expert on IIS myself, but it would be great to hear what you find works best for this. Or if anyone else has ideas to share on what has worked for them.
