### ISSUE TITLE
uninstall and reinstall looking for index.json in /flatcontainer/sleet/index.json

### ISSUE THREAD

**Issue by medianotion** [emgarten/Sleet#148]
I had to rebuild my computer.  Restored from backup.  I think this is a cache or configuration issue on my end.  But I am hoping someone can help me.

My sleet repo in package manager was not showing all my packages.  Oddly, I could clone an old project and restore could find the missing packages.  But I couldn't make a new project and add an existing nuget package because my package manager wasn't showing them all.

I thought it was something I could correct by uninstalling and reinstalling sleet.

I did : dotnet tool uninstall -g sleet 

Sleet uninstalled successfully.

I then did; dotnet tool install -g sleet

I get the following error:

C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : Unable to load the service index for source https://my-repo-domain-here/flatcontainer/sleet/index.json. [C:\Users\<username>\AppData\Local\Temp\va3ft15z.kq1\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\<username>\AppData\Local\Temp\va3ft15z.kq1\restore.csproj]

Its looking in flatcontainer/sleet/index.json for the index.json.  Which doesn't exist.  index.json is at the root.

Does anyone know how I can change the sleet install to find the index.json in the correct location of :  https://my-repo-domain-here/index.json   ????

Please let me know.

**Comment by emgarten** [comment]
@medianotion normally this would be on nuget.org, it looks like your NuGet.Config is pointing to another feed.

Try `dotnet tool install -g sleet --add-source https://api.nuget.org/v3/index.json`

**Comment by medianotion** [comment]
@emgarten  thank you for the response.  It didn't work but it lead me to the problem.  My nuget.config still had my sleet repo defined in it.  I removed that and sleet installed fine.

So anybody that needs to uninstall and reinstall will need to make sure they remove their sleet repo from nuget.config before reinstalling.

**Comment by emgarten** [comment]
Thanks for posting the solution. I'm glad you were able to fix it.
