### ISSUE TITLE
VS Package Manager browse only displays 25 packages 

### ISSUE THREAD

**Issue by medianotion** [emgarten/Sleet#149]
My VS package managers is only showing my first 25 packages.  Restore will restore packages not showing in the browse window.

I've seen this problem come and go in the past.  But now I'm on a new computer its constant.

Unless I use command line, I can't add packages to my projects that are past the 25 that are shown in the package manager browse window.

My sleet is configured to use S3 and it is private.  Cloudfront is delivering the listing.  I set the TTLs on cloudfront to 0 to avoid any caching.  I have also invalidated the cache to try to prevent any caching.

Is sleet paging list operations and possibly stopping for some reason?  Its odd that it is exactly 25 packages that it shows.  That is why I ask.

Is there a sleet local cache that I can clear to force it to pull down the entire package list?

Is there a way to force sleet to never use cache and to always pull latest from the repo?

**Comment by emgarten** [comment]
@medianotion you can run search for a Sleet feed to page the results. Here is an azure functions example I've made https://github.com/emgarten/Sleet.Search

I don't know of a lambda version so feel free to share it if you get it working there.

Issue tracking client side support for static search:
https://github.com/NuGet/Home/issues/9726

Here is the change in NuGet to limit search which is what you are hitting 
https://github.com/NuGet/NuGet.Client/pull/3406
