### ISSUE TITLE
How to integrate into a NuGet.Server Feed

### ISSUE THREAD

**Issue by DoCode** [emgarten/Sleet#15]
How can this v3 feed generator integrated into a [NuGet.Server](https://github.com/NuGet/NuGet.Server) (v2 Feed)?
Is this possible?

**Comment by DoCode** [comment]
Thanks, Justin.
I had an on-premise v2 feed (incl. authorization w/ AD) based on NuGet.Server. Now, I will provide a v3 feed in parallel to the existing v2 feed.

**Comment by emgarten** [comment]
For on-prem feeds v2 is often a good choice.  v3 is designed for static files, scaling, and with sleet it is easy to host them on an azure storage account with no compute required.

v3 feeds have some optimizations over v2 feeds for finding packages during PackageReference restore, but for a local server the time it takes to request several pages of packages from a v2 feed is going to be fairly low already.

Hosting both a v2 and v3 of the same feed may not give you any benefits.

**Comment by DoCode** [comment]
But the v2 feed is also accessed from outside the internal network.

The NuGet.Server v2 feed stores the packages at the filesystem. Is it not possible to provide an additional v3 feed based on the v2 packages? When they changed after an nuget push command?

**Comment by emgarten** [comment]
I think there are couple options for this

1. NuGet.Server could add support for v3 also
1. You could mirror the v2 feed to a v3 feed

There hasn't been any work done on the first option since there is no clear benefit of providing two ways to get the same packages, and currently all nuget clients support v2. There are no v3 only clients.

**Comment by emgarten** [comment]
I think this has been answered. Let me know if you have any other questions on this @DoCode

**Comment by joelverhagen** [comment]
Note that someone has asked a similar question about NuGet.Server on the NuGet team's server issue tracker:
https://github.com/NuGet/NuGetGallery/issues/5038
