### ISSUE TITLE
Sleet with Apache2 (on a classic Linux server) with authentication?

### ISSUE THREAD

**Issue by emmenlau** [emgarten/Sleet#153]
Dear @emgarten , I just found this awesome project and it seems to be exactly what we need. We want to host a small number of NuGet packages on a plain old classic Linux server (with Apache2).

Now my question is about authentication. I found in https://github.com/emgarten/Sleet/issues/144#issuecomment-757734361 that supposedly the NuGet clients would support some basic http authentication. Did I understand this correctly? And how would this be set up? Does it require the help of sleet? Or does a plain "classic" Basic HTTP authentication (like https://httpd.apache.org/docs/2.4/mod/mod_auth_basic.html in Apache) work with NuGet clients?

I can see that this question is a bit off-topic, since it is more centered around using sleet. But it may be very helpful for future users to have this documented, and any help would be greatly appreciated!

**Comment by emgarten** [comment]
`.htaccess` with apache should work for basic auth.

I haven't tested NuGet against a feed using apache before so let me know if you get it set up and can try it.

**Comment by emmenlau** [comment]
Ok that sounds very promising! I'll give it a try and let you know how it goes...
