### ISSUE TITLE
Support for Linux?

### ISSUE THREAD

**Issue by emmenlau** [emgarten/Sleet#154]
Dear @emgarten ,
this issue is a follow-up of #153 . Please forgive if my question is naiive: I've failed to build Sleet on Linux. Is this possible? It seems dotnet should be very well suited for cross-platform development, but when I run the build it says that `netcoreapp3.1` or `netstandard2.1` are unsupported target frameworks and my Linux would lack `net5.0` support. Is there some way how to run Sleet on Linux?
Thanks a lot for your help!

**Comment by emgarten** [comment]
Does running `build.sh` in the repo root work for you? It should download dotnet to the `.cli` folder and run standalone using that.

The logs from the linux CI machine on Travis are here: https://travis-ci.com/github/emgarten/Sleet

**Comment by emmenlau** [comment]
Thanks again for the quick reply! I see that dotnet 5 for Linux is also available, I was just not aware of that. Closing the issue as resolved!
