### ISSUE TITLE
Always support latest dotnet LTS in Sleet tool package

### ISSUE THREAD

**Issue by emgarten** [emgarten/Sleet#157]
* Going forward the Sleet tool package on nuget.org will keep support for dotnet LTS
* Current dotnet 5.0 package should move to dotnet 6.0 once it has been released.
* Future versions should continue to support the last LTS and the latest non-LTS if a newer version is available (ex: .NET 7).

**Comment by loic-sharma** [comment]
FYI we're about to release .NET 6 next week which will be LTS. I believe .NET 3.1 will be out of support next year. It may be better to just upgrade to .NET 6.

**Comment by emgarten** [comment]
Thanks for pointing that out @loic-sharma, moving everything to .NET 6 sounds like a better solution. 

Based on [dotnet release plan](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) it looks like dotnet 5 is only supported for 6 months after .NET 6 is out (less than 3.1).
