### ISSUE TITLE
Checking for nuspec should be case insensitive

### ISSUE THREAD

**Issue by jcagme** [emgarten/Sleet#16]
In line https://github.com/emgarten/Sleet/blob/e11393ab4bc720dc80cfd83adc0ab4cefe8d92b6/src/SleetLib/Commands/PushCommand.cs#L222 "nuspec" name is composed by the package identity id + ".nuspec". 

Normally this maps to the nuspec file name but if the casing is different when calling zip.GetEntry in line 223 then it will consider as if there was no nuspec since GetEntry is case sensitive.

A sample of how this breaks is package SQLite version 3.12.2-alpha. 

If you need the actual package let me know and I'll share it

**Comment by emgarten** [comment]
Fixed with https://github.com/emgarten/Sleet/commit/98f82378625f53f7cae497557a34af0bc343face
