### ISSUE TITLE
How to get connection string for Azure?

### ISSUE THREAD

**Issue by vonj** [emgarten/Sleet#166]
https://github.com/emgarten/Sleet/blob/main/doc/feed-type-azure.md

Looking at the docs, I don't understand what to put in connectionString?

I can only create a key, but it does not look at all like the sample connectionString.

**Comment by emgarten** [comment]
In the azure portal go to the storage account and go under `Access Keys`

From there you will see `key` and below that `connection string`

**Comment by jakobwn** [comment]
What if you do not wish to use static keys, but rather the current user / managed identity ?

**Comment by emgarten** [comment]
> What if you do not wish to use static keys, but rather the current user / managed identity ?

Tell me more about your environment, would sleet be using the managed identity of the VM it is running on?
