### ISSUE TITLE
Pagination not working on Visual Studio

### ISSUE THREAD

**Issue by AxlBlaK** [emgarten/Sleet#171]
It seems you can't handle more than 25 packages.
If there are more than 25 packages, the list restarts from the first one and the others cannot be viewed, even if you put the search filter by name

**Comment by emgarten** [comment]
I believe this is a NuGet client change to keep it from loading a very large search page.

You can fix it by running an external search provider service for your feed: https://github.com/emgarten/Sleet/blob/main/doc/external-search.md
