### ISSUE TITLE
visual studio prompts a login window while using s3 

### ISSUE THREAD

**Issue by danielwu223** [emgarten/Sleet#172]
Hello, I pushed some packages to our s3 bucket. in the NuGet.config file I used s3_path_to_index.json as the value of the package source, and then every time I opened up the Nuget management it asked me to log in, with the username and password required. I have the credential file in place and the env parameters with access key id and secret key. 
Am I doing anything wrong here with the configuration of fetching the package via visual studio?

Thanks

**Comment by danielwu223** [comment]
ah, ok, thanks, saved me a lot of time.

**Comment by danielwu223** [comment]
oh, one thing you might already know, your link at the bottom of the S3 document, about a private s3 bucket, hosted on LinkedIn, is broken.

**Comment by beeradmoore** [comment]
Article can be accessed via internet archive.

https://web.archive.org/web/20210122003915/http://kynatro.com/blog/2018/01/03/a-step-by-step-guide-to-creating-a-password-protected-s3-bucket/

@emgarten , I am still getting this same problem when using the CloudFront distribution method. I have not connected any of the private password stuff that is gone over in the above article. Just plain old CloudFront pointing to S3.

I can access `https://cloudfronturl.com/index.json` in my browser, so I assume CloudFront is working. I used the `path` property in my `sleet.json` to be the correct path and have re-created + invalidate CDN of my custom feed. I have also deleted nuget cache (as well as nuget http cache) from my machine and rebooted.

My nuget.config relative to my project has `<add key="mycustom-nuget" value="https://cloudfronturl.com/index.json" />` in it. I am unsure if `protocolVersion="3"` is required but I seem to get the same result with and without it.

Opening nuget browser in VS4Mac it lists my custom packages fine, but when I go to install that is when I get the password prompt. The package console window has this output,
```
Getting restore information for project /Users/bradmoore/Projects/ConsoleTest1/ConsoleTest1/ConsoleTest1.csproj
Running restore with 12 concurrent jobs.
Reading project file /Users/bradmoore/Projects/ConsoleTest1/ConsoleTest1/ConsoleTest1.csproj.
Restoring packages for /Users/bradmoore/Projects/ConsoleTest1/ConsoleTest1/ConsoleTest1.csproj...
Restoring packages for .NETCoreApp,Version=v7.0...
Resolving conflicts for net7.0...
Checking compatibility of packages on net7.0.
Checking compatibility for ConsoleTest1 1.0.0 with net7.0.
Checking compatibility for MyCustomPackage 1.0.4 with net7.0.
Checking compatibility for System.Text.Json 5.0.1 with net7.0.
All packages and projects are compatible with net7.0.
Response status code does not indicate success: 403 (Forbidden).
```
I am unable to see here, or in macOS console what URL is being hit that is forbidden. I can't see a way to increase the verbosity of the package console in Visual Studio for Mac. 

Is it possible there are some new endpoints during install that Visual Studio for Mac is trying to hit but sleet does not provide?

I'll try cli and I'll try on Windows and see if I get the same result.

**Comment by emgarten** [comment]
Great write up @beeradmoore, I think this would be useful as a doc under `/doc/` for AWS + Cloudfront if you're interested in adding it there.

**Comment by beeradmoore** [comment]
Good idea. I am currently writing it all up as a blog post, but I'll adapt the above for `/doc/` in this repo as well.

**Comment by emgarten** [comment]
I've written up a guide to creating a private feed based on examples in this issue: https://github.com/emgarten/Sleet/blob/main/doc/private-feed-s3.md
