### ISSUE TITLE
Wiki Wording Issue on Item "Delete"

### ISSUE THREAD

**Issue by WernerMairl** [emgarten/Sleet#19]
see: https://github.com/emgarten/Sleet/wiki/Command-reference#options-3

> **Delete**
>**Push adds** packages to your feed. It can used to **add** individual packages or complete directories of >packages.

Item=Delete, Text = "Push"... 

regards
Werner

**Comment by emgarten** [comment]
Fixed, thanks for catching that @WernerMairl!
