### ISSUE TITLE
Error Uri is not rooted in the basePath with 6.0.1

### ISSUE THREAD

**Issue by perpetualKid** [emgarten/Sleet#197]
Our pipeline started failing with below error yesterday, which seems to be related to the new sleet version 6.0.1.

`[System.ArgumentException] Uri https://storageaccount.blob.core.windows.net/ is not rooted in the basePath: https://storageaccount.blob.core.windows.net/builds`/

this is the command used:
```powershell
$feed='builds'
dotnet tool run sleet push .\..\..\a --config none -p SLEET_FEED_TYPE=azure -p SLEET_FEED_CONTAINER=$feed -p SLEET_FEED_CONNECTIONSTRING=${env:connectionstring}
```

Rolling back/fixing sleet version to 5.2.12 or prior fixes that for the moment.

**Comment by emgarten** [comment]
Thanks for the report, I'll take a look

**Comment by emgarten** [comment]
This has been fixed in https://www.nuget.org/packages/Sleet/6.0.3

**Comment by perpetualKid** [comment]
> This has been fixed in https://www.nuget.org/packages/Sleet/6.0.3

confirmed works, thanks for quick action!
