### ISSUE TITLE
Setting up a local V3 feed

### ISSUE THREAD

**Issue by MPTG94** [emgarten/Sleet#2]
I am using sleet to create a personal V3 feed which contains most of the packages from the official Nuget feed for an on-premise  closed environment.

I managed to use `sleet push` to generate all of the necessary files (index.json, packageindex, catalog, autocomplete, etc...)

I am now trying to publish my feed via an ASP.NET IIS website which exposes the V3 index.json.

However, I am faced with an error when trying to browse my repo using the Visual Studio package manager:

```
[Custom Nuget] Only 'http' and 'https' schemes are allowed.
Parameter name: requestUri
```

My Custom Nuget configuration in VS2015:
```
Name: Custom Nuget
Source: http://nuget-test/index.json
```

Where nuget-test is a server running an empty ASP.NET web template with the `Nuget.Sever` package installed

All of the packages are stored locally on the server nuget-test.
The ASP.NET website was made using the [guide on nuget.org](https://docs.nuget.org/create/hosting-your-own-nuget-feeds)

What am I doing wrong?

Also, I don't know how common of a use case this is but I think it's worth adding a guide on how to setup a local nuget feed using a personal sever and not one that is hosted on Azure

**Comment by emgarten** [comment]
> I think it's worth adding a guide on how to setup a local nuget feed using a personal sever and not one that is hosted on Azure

I agree, that would be helpful I'm hoping to work more on that setup next.

The json files created by Sleet can be served as static content, you do not need NuGet.Server.

One thing to note on hosting this way is that you'll need to set the path in your sleet.json file http://nuget-test/ so that the server output urls match the json content.

**Comment by MPTG94** [comment]
How should I configure my ASP.NET website so that when a call to http://nuget-test/index.json is made the file is served and the rest of the links (flatcontainer, catalog, autocomplete etc...), Are served when requested?

**Comment by emgarten** [comment]
I'll create an example and some web helpers for fixing urls to match the request.

**Comment by MPTG94** [comment]
#3 I added a PR with the updated quickstart guide.

**Comment by emgarten** [comment]
Fixed with @MPTG94's PR
