### ISSUE TITLE
Usability/exception wording Issue for Azure

### ISSUE THREAD

**Issue by WernerMairl** [emgarten/Sleet#20]
Hi
working with your project (nice!!) i found some detail that can be improved.

Steps to reproduce:
1. do a "createconfig" for Azure
2. do a "init" for that azure config WITHOUT changing the json file from step 1.

expected result: 
- doing the init should not be possible because the azure account is not configured (json file not changed)
- expecting a meaningfull exception message

found result/exception message: 
`[System.FormatException] No valid combination of account information found.`

The exception is coming from the Azure client and not helpful (not the exception type, not the message, not one word about azure context)

Suggest to provide more context in that error message.

There are multiple ways to improve that....
please give a look at the following:
https://github.com/WernerMairl/Sleet/commit/d9db17236e63e3c27d59424bb1d07deaabfe306c

i can create a PR...

regards
Werner

**Comment by emgarten** [comment]
Using a constant for the empty connection string and checking against it looks like a great idea. Send a PR :1st_place_medal:

**Comment by emgarten** [comment]
Fixed with https://github.com/emgarten/Sleet/commit/d357f0a6c0c22ef1cabeeaae5a90a32babb561c5

This change is in the latest version of Sleet on nuget.org
