### ISSUE TITLE
[Question] Unlisting a package

### ISSUE THREAD

**Issue by JinShil** [emgarten/Sleet#201]
Is there a way to unlist a package so that it is still installable, but doesn't appear in package searches?  I'm trying to accomplish the same thing as Nuget.org does here:  https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package

**Comment by emgarten** [comment]
Unlisting currently isn't supported by sleet. 

You could manually edit `/search/query` to remove it as a workaround.

**Comment by JinShil** [comment]
Thank you.
