### ISSUE TITLE
Issue in getting the file from S3 bucket

### ISSUE THREAD

**Issue by sndpyadav34** [emgarten/Sleet#206]
Hi Team,

We're using sleet tool to push required packages in one of my bucket. It's working perfectly fine and uploaded the packages. 
Now, as per the documentation(https://github.com/emgarten/Sleet/blob/main/doc/feed-type-s3.md), I'm able to consume all those packages using the package source url(_https://s3.amazonaws.com/my-bucket-feed/index.json_).
Now, as mentioned in the documentation(https://github.com/emgarten/Sleet/blob/main/doc/private-feed-s3.md), we tried to host our custom api to interface with S3 instead of using CloudFront. 
After uploading a sample nuget package using Sleet push command, we tried to read the contents of index.json file and are running into issue.

Code

```
var s3Client = new AmazonS3Client("test", "test", amazonS3Config);
var response = await s3Client.GetObjectAsync(new GetObjectRequest
{
    BucketName = "test-nuget-packages-private-xxx",
    Key = "index.json"
});
 
byte[] responseBytes;
using (var memoryStream = new MemoryStream())
{
    await response.ResponseStream.CopyToAsync(memoryStream, CancellationToken.None);
    responseBytes = memoryStream.ToArray();
}
var index_str = Encoding.UTF8.GetString(responseBytes);
```
The issue being observed is that we are unable to read the "index.json" file uploaded by Sleet and are receiving truncated binary content. Please refer screenshot below as the string is all binary and cannot be converted to plain text or cannot be deserialized in any way. Please note the byte length is 469 which is less than contents of the file.
![image](https://github.com/user-attachments/assets/f7f56ded-8ec8-4623-b248-5919cb519ea3)

What we did next was to download the contents of the "index.json" file from S3 bucket and then locally create a new JSON file by pasting those contents. We uploaded this test file as "sample_index.json" and then tried reading this file using AWS S3 .NET SDK's S3 Client and are able to read it successfully. Please refer below screenshot which shows the content is proper and also the byte length is 1181 which matches the file size.

![image](https://github.com/user-attachments/assets/e471e0bf-e7d7-4985-a7af-3a12a2c6f051)

Attaching both the index files for reference
index.json - This file was created by Sleet in S3 bucket as part of package push using Sleet push command.
sample_index.json - This file was created by manually copying the contents of index.json file from S3.
[index.json](https://github.com/user-attachments/files/17568364/index.json)
[sample_index.json](https://github.com/user-attachments/files/17568366/sample_index.json)

Please let us know if this is something related to serialization or encoding that we're not able to read these files from S3.
All we want to do is host our custom api as frontend to access the packages in S3. Our custom api has our custom authentication implemented.

**Comment by sandeepkumar-conga** [comment]
Hi Team, we figured out, this was due to compression.

```var response = await s3Client.GetObjectAsync(getRequest);
using (Stream csStream = new GZipStream(response.ResponseStream, CompressionMode.Decompress))
using (var reader = new StreamReader(csStream))
{
    jsonData = await reader.ReadToEndAsync();
}
```
The above code snippet should solve that issue.
Thanks

**Comment by sndpyadav34** [comment]
Hi Team, we figured out, this was due to compression.

Following code snippet should solve this issue
```
using (Stream csStream = new GZipStream(response.ResponseStream, CompressionMode.Decompress))
using (var reader = new StreamReader(csStream))
{
    jsonData = await reader.ReadToEndAsync();
}
```

Thanks

**Comment by sndpyadav34** [comment]
Hi Team, we figured out, this was due to compression.

Following code snippet should solve this issue
```
using (Stream csStream = new GZipStream(response.ResponseStream, CompressionMode.Decompress))
using (var reader = new StreamReader(csStream))
{
    jsonData = await reader.ReadToEndAsync();
}
```
Thanks

**Comment by emgarten** [comment]
Compressed files have Content Encoding set to `gzip`. For all json files Sleet will compress them to improve perf for the client. https://github.com/emgarten/Sleet/blob/df1a358d631718126dfda19e9b0663ad8a893462/src/SleetLib/FileSystem/AmazonS3File.cs#L119

When you read the bucket directly using the S3 SDK you need to account for this like your code snippet shows. If you are reading the file from a public HTTP url using a standard http client the client will automatically decompress it for you when it sees the content encoding type.
