### ISSUE TITLE
Add instructions for symbol server

### ISSUE THREAD

**Issue by skarllot** [emgarten/Sleet#30]
The documentation should include the directions to configure a symbol server.

**Comment by emgarten** [comment]
Docs for this would be great. For the most part the feed just needs the setting turned on, or it needs to be set during init. After that users should just need to know how to determine the symbols url for the feed to use in their debugger.

**Comment by emgarten** [comment]
Take a look at: https://github.com/emgarten/Sleet/blob/master/src/SleetLib/Utility/SymbolsUtility.cs

The dll and pdb files are put under hash directories, and that hash is determined from metadata in the dll. Possibly you have a type of dll that the current pdb reader can't read, or there is a bug in the utility.

**Comment by emgarten** [comment]
How are you consuming the symbols server? Are you using visual studio?

The root symbols path will be in the root index.json file of the feed.

**Comment by skarllot** [comment]
> How are you consuming the symbols server? Are you using visual studio?

Yes, I'm using Visual Studio.

> The root symbols path will be in the root index.json file of the feed.

I was trying pointing to symbols folder.

**Comment by emgarten** [comment]
That should work, try both a trailing slash, and no trailing slash on the symbols url.

You could also verify that VS is requesting the url that exists on the feed by using fiddler to watch the network calls going out.

**Comment by emgarten** [comment]
I've moved docs from the wiki to https://github.com/emgarten/Sleet/blob/master/doc/index.md  to make documentation easier. 

I haven't had a chance to write up a symbols server doc yet, but I hope to soon.
