### ISSUE TITLE
Azure feed with BaseURI fails

### ISSUE THREAD

**Issue by emgarten** [emgarten/Sleet#34]
Steps
1. Create a new azure feed
1. Set `baseURI` in sleet.json
1. Init

```
E:\tmp> .\Sleet.exe init --verbose
[System.InvalidOperationException] Unable to make 'https://example.com/test/sleet.settings.json' relative to 'https://sleettestfeed.blob.core.windows.net/basetest/'
```

This works for local feeds, but not for azure feeds.

//cc @natemcmaster

**Comment by emgarten** [comment]
I've done some clean up around how baseURI is handled. This is fixed now and I've added an azure test to verify it.

**Comment by natemcmaster** [comment]
Awesome, thanks Justin!

**Comment by natemcmaster** [comment]
I just tried this in the latest build, 2.3.25, and I'm getting an error again. Am I doing something wrong? I don't think I ever actually verified https://github.com/emgarten/Sleet/commit/fac2e3bc58028a666b3d45e079deeb0ee9613ce0 because I was using the publish-to-local-then-upload workaround.

```json
{
  "sources": [
    {
      "name": "feed",
      "type": "azure",
      "path": "https://nmcmastertest.core.windows.net/testpush/",
      "feedSubPath": "testpush/aspnetcore/store/123/packages/",
      "baseURI": "https://nmcmastertest.proxy.example.com/testpush/aspnetcore/store/123/packages/",
      "container": "testpush",
      "connectionString": "DefaultEndpointsProtocol=https;AccountName=aspnetcore;AccountKey=xxxxxx"
    }
  ]
}
```
```
[System.ArgumentException] Uri https://nmcmastertest.core.windows.net/testpush/ is not rooted in the basePath: https://nmcmastertest.blob.core.windows.net/testpush/
```

**Comment by emgarten** [comment]
`FeedSubPath` is for creating a sub folder in the container. Try removing that entry in the config. It shouldn't change the URI written out to file, it just changes where the files are actually written out.

**Comment by emgarten** [comment]
```
https://nmcmastertest.blob.core.windows.net/testpush/ - Works 
https://nmcmastertest.core.windows.net/testpush/ - Fails
```

Sleet is trying to auto figure out the feedSubPath by comparing the value of `path` from the config to what the storage SDK gives for the container URI.

This should be handled better by Sleet. Either it should be able to determine that those paths are actually the same, or it should skip this extra validation since it already knows the real container path.

https://github.com/emgarten/Sleet/blob/3a77194bf89a12c0755af60320161a07a8f52e8a/src/SleetLib/FileSystem/AzureFileSystem.cs#L34-L35

**Comment by emgarten** [comment]
Not really a user error! 😄  The config settings are confusing right now, I'll keep this open to track documenting them and improving the error messages.

**Comment by emgarten** [comment]
Fixed with https://github.com/emgarten/Sleet/commit/73cb67da691c9e3a5e0a32807177a6f000c940f4

I've removed `path` as a required property for azure feeds. If you leave it out of the config it will now resolve it from the container URI automatically.  When you specify it, it will verify that it is correct, and if not error out with the container URI and path side by side.
