### ISSUE TITLE
Update global CLI tool to netcoreapp2.1

### ISSUE THREAD

**Issue by natemcmaster** [emgarten/Sleet#35]
The latest sleet package doesn't work with the 2.1.300-rc1 SDK as a global tool anymore. The CLI team is making netcoreapp2.1 a minimum requirement for CLI tool packages. https://github.com/dotnet/cli/issues/9073

**Comment by emgarten** [comment]
Is this enforced already? Do I need to update it to 2.1 to unblock you or is this going to happen closer to the release?

**Comment by natemcmaster** [comment]
This requirement was quietly added in preview2, so sleet doesn’t work anymore as a global tool. They’re adding enforcement in rc1

**Comment by emgarten** [comment]
Fixed in https://www.nuget.org/packages/Sleet/2.3.22

Sleet now has netcoreapp2.1 support
