### ISSUE TITLE
Any thought about the ability to read configuration items via environment variables?

### ISSUE THREAD

**Issue by mwhitis** [emgarten/Sleet#39]
Just wondering if you've thought of supporting the ability to get the configuration items from env vars or another source instead of just sleet.json?  Our azure data storage has a key in the url, and we'd like to not check that into our repo in the sleet.json.

Alternately, are you open to considering a pull request with the same?

Thanks

**Comment by emgarten** [comment]
In the past I've considered either having values come from env vars such as `sleet_path`, or sleet.json could contain something like `$storagekey$` that would resolve to the env var value.

Any other ideas? What would work best for your scenario?

I'd be happy to accept a PR for this, it would be a great feature. 🍰

**Comment by emgarten** [comment]
In the sleet.json file sounds best to me also.

NuGet has `.pp` files which support env var substitutions. Sleet.json could work the same.
1. Parse the file as json
1. Loop through all key/values and if `$key$` matches an env var replace it
1. `$$` is used for escaping to get a `$`

**Comment by emgarten** [comment]
@mwhitis any thoughts on this?

**Comment by emgarten** [comment]
@mwhitis I've added support for tokenized sleet.json files as well as env variables. The more I dug into some of my own CI scenarios the more reasons I found to allow also not having any config on disk.

I've written up how to use it in: https://github.com/emgarten/Sleet/blob/master/doc/client-settings.md#tokens-in-sleetjson
