### ISSUE TITLE
Relative "path" setting

### ISSUE THREAD

**Issue by mungojam** [emgarten/Sleet#49]
It would be useful if we had the option to use a relative path for the 'path' option, with it relative to the config file itself (like nuget.config allows). I tried it with both `".\\"` and `""` but both gave errors about invalid URIs

When running:
> sleet push --config path_to_config.json -s myLocalFeed path_to_nupkg

```javascript
{
  "username": "",
  "useremail": "",
  "sources": [
    {
      "name": "myLocalFeed",
      "type": "local",
      "path": ".\\",
      "baseURI": "https://mungojam.github.io/sleet-test/"
    }
  ]
}
```
> [System.UriFormatException] Invalid URI: The format of the URI could not be determined.

```javascript
{
  "username": "",
  "useremail": "",
  "sources": [
    {
      "name": "myLocalFeed",
      "type": "local",
      "path": "",
      "baseURI": "https://mungojam.github.io/sleet-test/"
    }
  ]
}
```
> [System.UriFormatException] Invalid URI: The URI is empty.

**Comment by emgarten** [comment]
I hadn't considered this scenario before, it would be handy to define local feeds with a relative path.

My guess is that the exception happens here: https://github.com/emgarten/Sleet/blob/2efe855c79e4a1fe17747016b418de3b7faab629/src/SleetLib/FileSystem/FileSystemFactory.cs#L41

A fix for this would be to check first if it is a local path for the local feed type, and then resolve the value against the current working directory before creating the file system here: https://github.com/emgarten/Sleet/blob/2efe855c79e4a1fe17747016b418de3b7faab629/src/SleetLib/FileSystem/FileSystemFactory.cs#L51

**Comment by mungojam** [comment]
Any chance of a new release? It would be good to be able to use this relative path feature

**Comment by emgarten** [comment]
There will be a release in the new few days. A perf change went in right before your changes, I'm working on testing that and then I'll get a release out.

**Comment by emgarten** [comment]
@mungojam this is available in https://www.nuget.org/packages/Sleet/2.3.49

**Comment by mungojam** [comment]
Super, thanks. I'll deploy it this week
