### ISSUE TITLE
Symbol packages

### ISSUE THREAD

**Issue by skarllot** [emgarten/Sleet#5]
Sleet could be symbol server too.

**Comment by emgarten** [comment]
I like the idea, do you know if this can be done with static files over http?

**Comment by skarllot** [comment]
Not yet. I'll do some research.

**Comment by emgarten** [comment]
@skarllot did you find out if this is possible with static files?

**Comment by skarllot** [comment]
@emgarten sorry, I didn't had much time.

Possible start point: https://msdn.microsoft.com/en-us/library/ff549776(v=vs.85).aspx

**Comment by emgarten** [comment]
Looks like a static feed could host this, I'll try it out.

**Comment by emgarten** [comment]
This will be part of the 2.0.0 release
