### ISSUE TITLE
Follow Recommended AWS Credential Management Practices

### ISSUE THREAD

**Issue by mlhpdx** [emgarten/Sleet#52]
It's great that Sleet supports S3, but the current implementation of `FileSystemFactory` requires an AWS access key and secret key to be entered into the `sleet.json` configuration file.  Since sleet is using the AWS SDK, this is unnecessary -- the SDK will search a series of locations on the instance/pc to find credentials -- and it is counter to the recommended practice. See the second bullet point here:

https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-creds.html

The two needed values are the bucket and region (the latter can't be determined without an S3 client, and the client can't be created without a region -- a nice catch-22).  Other than that, an optional AWS profile name would be the way a developer can instruct the SDK to find one of several configured profiles.

I'll follow-up this issue with a PR, but the minimal change is to simply not require the keys to be configured (remove those lines) and use a different constructor for the S3 client when the keys are not provided:

```new AmazonS3Client(regionSystemName)```

Adding an optional "profile name" value is a little more involved, obviously.

Thanks for Sleet, by the way, it's awesome.

**Comment by emgarten** [comment]
Fixed with https://github.com/emgarten/Sleet/pull/54
