### ISSUE TITLE
Sort out the usage of relative paths for local feeds

### ISSUE THREAD

**Issue by inosik** [emgarten/Sleet#59]
_From #50:_

I tried to start from scratch and changed the path in the generated `sleet.json` file from an absolute path to a relative one:

```json
{
  "username": "",
  "useremail": "",
  "sources": [
    {
      "name": "my-feed",
      "type": "local",
      "path": "my-feed",
      "baseURI": "https://example.com/feed/v3"
    }
  ]
}
```
 Initializing the feed doesn't work:

```shell
$ sleet init --source my-feed
[System.ArgumentException] Cannot use a relative 'path' without a settings.json file.
```

`settings.json` should be `sleet.json`, because that's what Sleet is looking for.

Sleet behaves differently if the path to the configuration is specified as an argument:

```shell
$ sleet init -c sleet.json --source my-feed
[System.UriFormatException] Invalid URI: The format of the URI could not be determined.
```

However, it works if the path to the configuration file is an absolute path:

```shell
$ sleet init -c `pwd`/sleet.json --source my-feed
Initializing https://example.com/feed/v3/
# more log messages ...
```

Or a relative path:

```shell
$ sleet init -c ./sleet.json -s my-feed
```

I certainly didn't expect `sleet.json` and `./sleet.json` to be handled differently.

**Comment by mungojam** [comment]
taking a look now

**Comment by emgarten** [comment]
@inosik this has been fixed in https://www.nuget.org/packages/Sleet/2.3.70
