### ISSUE TITLE
Clean catalog

### ISSUE THREAD

**Issue by Nazgul07** [emgarten/Sleet#6]
I am currently using this to upload the latest builds of an in development project to Azure Blob storage, and we are only keeping the latest builds in the nuget feed. As silly as it may sound we are always uploading the same "version" of our package ie: package.1.0.0.1234.nupkg. It is this way because we are creating chocolatey packages for our pre-built versions of our software. However, the page.0.json file keeps growing along with the json files in the catalog\data folder. I realize this keeps transaction history, but (it may just be my imagination, there's probably no correlation) it seems like our uploads are slowing down the longer this gets, also I just don't like having it hanging out there when we don't need it.

Would it be possible to have a flag on the push command to update in-place without adding transaction logs or possibly a new command to clear the logs out?

**Comment by emgarten** [comment]
The ``recreate`` command that was recently added will download all packages and rebuild the feed without the history, this would clear out the logs.

How many entries does your page.0.json have? I'm wondering if there is a bug there that it isn't moving to a new page, or if the page size is set too high. Ideally it should only have to download and modify the latest page, which should be minimal.

An option to leave the history out sounds useful also.

**Comment by Nazgul07** [comment]
I currently have 1013 entries, I found that the page size is 1024 by searching the code, so it's about to turn a page. I guess I'll see if uploading improves at all once it turns.

Our automated build process publishes 10 packages at once totaling ~850MB. The `recreate ` command would probably work for now because at the moment we are always uploading the same package version, but eventually we will be uploading multiple package versions on a rolling basis, and I would hate to recreate the whole feed every time.

Really it's all probably about my perception...I understand this really isn't a big issue all told, mostly I just like tidiness. I fully envision our catalogs to get >10-50K entries if we can't clean them. The OCD in me is coming out.

**Comment by emgarten** [comment]
How about if there was an option to turn the catalog/history off for a feed? This would avoid writing the extra files.

**Comment by Nazgul07** [comment]
I would love that.

**Comment by emgarten** [comment]
Fixed with Sleet@ab75459b92f5ef38de63becf9fd62c41718a6948

**Comment by emgarten** [comment]
@Nazgul07 you can get the latest version of Sleet.exe here: https://nuget.blob.core.windows.net/packages/flatcontainer/sleet/2.0.0-beta.19/sleet.2.0.0-beta.19.nupkg

To update your feed use:
``Sleet.exe recreate -s <source name> -c <sleet.json path>``

By default the catalog will be disabled. I've also made a change to push files to the feed in parallel which should help performance. 

Let me know if you hit any issues with the beta build.
