### ISSUE TITLE
Use system proxy with S3

### ISSUE THREAD

**Issue by mungojam** [emgarten/Sleet#63]
It seems that I am hitting [this](https://github.com/dotnet/corefx/issues/24574) limitation in dot net core when I try any sleet commands with S3

We have a proxy which windows knows about and which I can make use of when using .net framework, by simply adding:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy useDefaultCredentials="true"></defaultProxy>
  </system.net>
</configuration>
```

to the app.config file. This doesn't seem to be supported by .net core though I expect there is a workaround. Any ideas if it should just work with proxies by default?

**Comment by mungojam** [comment]
I've now tried building my own .net framework console app with the above proxy settings and using SleetLib. When calling InitCommand, it reckoned that the bucket didn't exist until I started fiddler which it seemed happy to proxy through and then worked fine.

It may be an issue with the AWS SDK

**Comment by mungojam** [comment]
I see now that the failure only happens when calling `client.DoesS3BucketExistAsync` which according to the docs at the top of the class:

> ICoreAmazonS3 is not meant to use directly

I wonder if there is a better method to use that will take account of the proxy settings. For example, I am able to use `ListBuckets` through the proxy. I see that the above method calls `AmazonS3Util.DoesS3BucketExistAsync` which not surprisingly doesn't work past the proxy.

Looking more like an issue with the SDK, the more I look

**Comment by mungojam** [comment]
It looks like all the lines like this, creating the S3 client:

https://github.com/emgarten/Sleet/blob/6b964317bda5515f1e68da551ec3daa439589ee5/src/SleetLib/FileSystem/FileSystemFactory.cs#L163

need to change to this to support proxy credentials:

```c-sharp
      var config = new AmazonS3Config()
	{
		RegionEndpoint = regionSystemName,
		ProxyCredentials = new NetworkCredential()
	};
      var client = new AmazonS3Client(profile.GetAWSCredentials(profileSource: null), config);
```

but I'm not clear how that works for people who don't have proxies or have basic auth proxies. The above is required even for .net framework. I've found that AWS SDK seems to have two styles within it, so some operations are fine with just the app.config setting while others require the above.

**Comment by emgarten** [comment]
If you send a PR a change that works on your machine with the proxy I can verify that it still works fine for me without it. 

There are also functional tests that run against an actual S3 bucket from the CI, they should catch any obvious problems also.

**Comment by emgarten** [comment]
@mungojam your fix has been released in https://www.nuget.org/packages/Sleet/2.3.77

**Comment by mungojam** [comment]
It looks like my fix failed miserably. The one time it worked must have been an odd fluke or I had done something else that made it work. I'll put together a better one once I can figure it out...

Feel free to revert my previous PR

**Comment by emgarten** [comment]
Is it worse with the fix, or is there no change for the proxy scenario?

**Comment by mungojam** [comment]
No change as far as I can tell. I have an idea how to fix it but will need more testing first

**Comment by emgarten** [comment]
Released in https://www.nuget.org/packages/Sleet/2.3.79

**Comment by mungojam** [comment]
I'm fully up and running now. Thanks for the quick releases and for a great tool!
