### ISSUE TITLE
Support SNUPKG format

### ISSUE THREAD

**Issue by skarllot** [emgarten/Sleet#72]
Support current symbol package format.

- Ref: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by loic-sharma** [comment]
For implementation details, see:

* [nuget.org upload code] (https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Services/SymbolPackageUploadService.cs)
* [nuget.org validations](https://github.com/NuGet/NuGet.Jobs/blob/master/src/Validation.Symbols/SymbolsValidatorService.cs#L44)
