### ISSUE TITLE
Packegs folder disappeared from flatcontainer

### ISSUE THREAD

**Issue by lukos** [emgarten/Sleet#78]
Over the weekend, a previously working installation stopped working for a specific package in our feed. On examination, the packages folder was deleted from inside flatcontainer but the the index file sleet.packageindex.json with the versions was still correct. The folder was still present underneath the registrations folder.

Obviously this caused nuget to fail installation on a client machine. We honestly can't think how that folder would have been deleted manually. Neither of the two people who have access did it and we don't go into those folders anyway since packages are pushed directly from the CI process.

Is there any way that Sleet might have deleted it for a reason that wasn't correct? Since the index files weren't cleaned up as well, I assume this would be a more subtle bug otherwise all traces would have gone?

Thanks

**Comment by emgarten** [comment]
Was this an azure, s3, or local feed? Could someone have manually done a recreate/destroy or anything apart from push? Is there any mention of deleting these files in the CI logs?

I'm not sure how the packages folder could have been removed. Sleet works by constructing file paths for most scenarios, it will directly fetch the files it changes as opposed to working with folders. When deleting a package for example, Sleet removes it by figuring out the nupkg path from the id/version. It doesn't need to list the folder, so I wouldn't think it could get into a situation where it would even know about the other nupkgs, let alone remove the whole folder.

**Comment by lukos** [comment]
Don't worry about it then. It is a local feed and we only deploy using `sleet.exe push` so that shouldn't have done anything.
We also don't have any admin or anything like that, the only thing I can think is that somehow the other admin must have deleted it without realising it using whatever he might have been running.

**Comment by emgarten** [comment]
Let me know if you see it happen again. I appreciate the issue, if there is a bug causing this I'd definitely like to track it down.
