### ISSUE TITLE
Public dependencies resolving to private feed

### ISSUE THREAD

**Issue by cpeth** [emgarten/Sleet#96]
I have a package that has some dependencies installed from the main public Nuget feed.  When I publish my package to a S3 private feed using Sleet then attempt to reference that package, Nuget attempts to get those public dependencies from the private feed and fails as they don't exist.  Is there a way to configure Sleet to use the public feed for public dependencies?
![nuget-dependencies](https://user-images.githubusercontent.com/433959/67814496-700a3680-fa61-11e9-8369-072a56e0f911.png)
![restore-fail](https://user-images.githubusercontent.com/433959/67814727-11918800-fa62-11e9-85e3-f383cda31754.png)

**Comment by loic-sharma** [comment]
Can you configure NuGet to have two package sources? You can use `dotnet new nugetconfig` to generate a `nuget.config` file, which you can configure to have multiple sources: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections

If using multiple package sources isn't an option, you can always publish of your public dependencies to your private feed.

**Comment by cpeth** [comment]
I had already referenced multiple package sources.

I got it to work.   I had the version of my package set to `*` in the `.csproj` file.  Setting it to `1.0.0` fixed the issue.  Thanks.

**Comment by emgarten** [comment]
`*` should have resolved `1.0.0` since it is a stable version.

I'm curious about the 403 errors, is your bucket policy set to only allow access to certain paths and unexpected package ids are getting errors?
