### ISSUE TITLE
"Waiting to obtain feed lock" Error

### ISSUE THREAD

**Issue by medianotion** [emgarten/Sleet#97]
Is anybody else getting this error with AWS?

When I go to my S3 bucket and look for .feedlock, I don't see one there to delete (per the error message instructions).

My build machine that is throwing this error is always installing the latest version of sleet for each build.

No other machine in my environment puts,deletes or otherwise locks the sleet repo.

Error message I am receiving:
"Waiting to obtain feed lock. Client holding the lock did not provide a message, it may be using an older version of Sleet. Delete <bucket here>/.feedlock to forcibly unlock the feed."

**Comment by emgarten** [comment]
Checking for a lock is one of the first bucket operations to happen, my guess is that an exception is thrown when trying to check for the file, or when creating the file, and it suppressed here: https://github.com/emgarten/Sleet/blob/aaba0f4efab480ded50e7c2d5117b1e2cd696c7a/src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs#L49

This catch block should log the error as either or a warning, or at minimum to the debug output so that it can be viewed with ``--verbose``

@medianotion are you able to make this change locally to see the exception thrown?

**Comment by medianotion** [comment]
I added the –verbose but it didn’t help.  No additional information provided.  See log entries below.

 

Log Entry

[Container] 2019/10/31 19:50:52 Running command dotnet tool install -g sleet 

You can invoke the tool using the following command: sleet 

Tool 'sleet' (version '3.0.18') was successfully installed.

……  build and nuget package creation happens here 

[Container] 2019/10/31 19:52:05 Running command if ($nuget_pkg) { sleet push --verbose $nuget_pkg -s aesto } else { write-host("No nuget package to push.") } 

Reading feed https://<mybucket>.cloudfront.net/ 

Reading Data.NoSQLService.1.0.0.nupkg 

Waiting to obtain feed lock. Client holding the lock did not provide a message, it may be using an older version of Sleet. Delete <mybucket>/.feedlock to forcibly unlock the feed

**Comment by medianotion** [comment]
I am sorry.  This was a permissions issue on my end.  Please close.

**Comment by emgarten** [comment]
@medianotion thanks for the update. I'm going to leave this open to track improving the warning/error here. It seems easy to run into.

**Comment by dandansoysauce** [comment]
@medianotion what was your permission issue? I'm having the same issue.

Thanks

**Comment by medianotion** [comment]
Sleet uses AWS credentials to access the S3 location where you have sleet storing your Nuget repo.

 

If you get this error, the AWS credentials being used by Sleet do not have permission to the S3 location.

 

Sleet uses the sleet.json file to find the AWS credentials it will use.  The sleet.json file can be configured to find AWS credentials in 3 ways:

 

1.	By hard coding the AWS credentials in the sleet.json
2.	By referencing an AWS profile (see your /user-name-here/.aws/credentials file) in your sleet.json file
3.	By finding credentials provided by the Role an AWS instance is running under.  This situation is only used if you are running sleet on an AWS Instance, CodeBuild, etc.  

 

I would suggest you discover the credentials that sleet is using and test whether those creds can read and write to the S3 location configured in your sleet.json file.

**Comment by emgarten** [comment]
The fix has been released in https://www.nuget.org/packages/Sleet/3.0.20

If you are still having problems but not seeing Sleet fail with an error message while trying to get the lock run with `--verbose`
